// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/yourorg/perspectize-go/internal/core/domain"
)

type CategorizedRating struct {
	Category string `json:"category"`
	Rating   int    `json:"rating"`
}

type CategorizedRatingInput struct {
	Category string `json:"category"`
	Rating   int    `json:"rating"`
}

type Content struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	URL          *string        `json:"url,omitempty"`
	ContentType  string         `json:"contentType"`
	Length       *int           `json:"length,omitempty"`
	LengthUnits  *string        `json:"lengthUnits,omitempty"`
	ViewCount    *int           `json:"viewCount,omitempty"`
	LikeCount    *int           `json:"likeCount,omitempty"`
	CommentCount *int           `json:"commentCount,omitempty"`
	Response     map[string]any `json:"response,omitempty"`
	CreatedAt    string         `json:"createdAt"`
	UpdatedAt    string         `json:"updatedAt"`
}

type ContentFilter struct {
	ContentType      *domain.ContentType `json:"contentType,omitempty"`
	MinLengthSeconds *int                `json:"minLengthSeconds,omitempty"`
	MaxLengthSeconds *int                `json:"maxLengthSeconds,omitempty"`
}

type CreateContentFromYouTubeInput struct {
	URL string `json:"url"`
}

type CreatePerspectiveInput struct {
	Claim              string                    `json:"claim"`
	UserID             int                       `json:"userID"`
	ContentID          *int                      `json:"contentID,omitempty"`
	Quality            *int                      `json:"quality,omitempty"`
	Agreement          *int                      `json:"agreement,omitempty"`
	Importance         *int                      `json:"importance,omitempty"`
	Confidence         *int                      `json:"confidence,omitempty"`
	Like               *string                   `json:"like,omitempty"`
	Privacy            *domain.Privacy           `json:"privacy,omitempty"`
	Description        *string                   `json:"description,omitempty"`
	Category           *string                   `json:"category,omitempty"`
	Parts              []int                     `json:"parts,omitempty"`
	Labels             []string                  `json:"labels,omitempty"`
	CategorizedRatings []*CategorizedRatingInput `json:"categorizedRatings,omitempty"`
}

type CreateUserInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type PaginatedContent struct {
	Items      []*Content `json:"items"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount *int       `json:"totalCount,omitempty"`
}

type PaginatedPerspectives struct {
	Items      []*Perspective `json:"items"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount *int           `json:"totalCount,omitempty"`
}

type Perspective struct {
	ID                 string               `json:"id"`
	Claim              string               `json:"claim"`
	UserID             string               `json:"userID"`
	User               *User                `json:"user,omitempty"`
	ContentID          *string              `json:"contentID,omitempty"`
	Content            *Content             `json:"content,omitempty"`
	Quality            *int                 `json:"quality,omitempty"`
	Agreement          *int                 `json:"agreement,omitempty"`
	Importance         *int                 `json:"importance,omitempty"`
	Confidence         *int                 `json:"confidence,omitempty"`
	Like               *string              `json:"like,omitempty"`
	Privacy            domain.Privacy       `json:"privacy"`
	Description        *string              `json:"description,omitempty"`
	Category           *string              `json:"category,omitempty"`
	ReviewStatus       *domain.ReviewStatus `json:"reviewStatus,omitempty"`
	Parts              []int                `json:"parts,omitempty"`
	Labels             []string             `json:"labels,omitempty"`
	CategorizedRatings []*CategorizedRating `json:"categorizedRatings,omitempty"`
	CreatedAt          string               `json:"createdAt"`
	UpdatedAt          string               `json:"updatedAt"`
}

type PerspectiveFilter struct {
	UserID    *int            `json:"userID,omitempty"`
	ContentID *int            `json:"contentID,omitempty"`
	Privacy   *domain.Privacy `json:"privacy,omitempty"`
}

type Query struct {
}

type UpdatePerspectiveInput struct {
	ID                 int                       `json:"id"`
	Claim              *string                   `json:"claim,omitempty"`
	ContentID          *int                      `json:"contentID,omitempty"`
	Quality            *int                      `json:"quality,omitempty"`
	Agreement          *int                      `json:"agreement,omitempty"`
	Importance         *int                      `json:"importance,omitempty"`
	Confidence         *int                      `json:"confidence,omitempty"`
	Like               *string                   `json:"like,omitempty"`
	Privacy            *domain.Privacy           `json:"privacy,omitempty"`
	Description        *string                   `json:"description,omitempty"`
	Category           *string                   `json:"category,omitempty"`
	ReviewStatus       *domain.ReviewStatus      `json:"reviewStatus,omitempty"`
	Parts              []int                     `json:"parts,omitempty"`
	Labels             []string                  `json:"labels,omitempty"`
	CategorizedRatings []*CategorizedRatingInput `json:"categorizedRatings,omitempty"`
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
