// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Content struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	URL          *string `json:"url,omitempty"`
	ContentType  string  `json:"contentType"`
	Length       *int    `json:"length,omitempty"`
	LengthUnits  *string `json:"lengthUnits,omitempty"`
	ViewCount    *int    `json:"viewCount,omitempty"`
	LikeCount    *int    `json:"likeCount,omitempty"`
	CommentCount *int    `json:"commentCount,omitempty"`
	CreatedAt    string  `json:"createdAt"`
	UpdatedAt    string  `json:"updatedAt"`
}

type CreateContentFromYouTubeInput struct {
	URL string `json:"url"`
}

type Mutation struct {
}

type Query struct {
}
