package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"fmt"
	"time"

	"github.com/CodeWarrior-debug/perspectize/backend/internal/adapters/auth"
	"github.com/CodeWarrior-debug/perspectize/backend/internal/adapters/graphql/generated"
	"github.com/CodeWarrior-debug/perspectize/backend/internal/adapters/graphql/model"
	"github.com/CodeWarrior-debug/perspectize/backend/internal/core/domain"
	portservices "github.com/CodeWarrior-debug/perspectize/backend/internal/core/ports/services"
)

// Sender is the resolver for the sender field.
func (r *messageResolver) Sender(ctx context.Context, obj *model.Message) (*model.User, error) {
	if _, ok := auth.ForContext(ctx); !ok {
		return nil, domain.ErrForbidden
	}
	u, err := r.UserService.GetByID(ctx, obj.SrcSenderID)
	if err != nil {
		return nil, err
	}
	return userDomainToModel(u), nil
}

// Participants is the resolver for the participants field.
func (r *messageThreadResolver) Participants(ctx context.Context, obj *model.MessageThread) ([]*model.ThreadParticipant, error) {
	if _, ok := auth.ForContext(ctx); !ok {
		return nil, domain.ErrForbidden
	}
	if obj.Src == nil {
		return []*model.ThreadParticipant{}, nil
	}
	out := make([]*model.ThreadParticipant, 0, len(obj.Src.Participants))
	for _, p := range obj.Src.Participants {
		if p.LeftAt != nil {
			continue
		}
		out = append(out, threadParticipantToModel(p))
	}
	return out, nil
}

// LatestSeq is the resolver for the latestSeq field.
func (r *messageThreadResolver) LatestSeq(ctx context.Context, obj *model.MessageThread) (int, error) {
	actor, ok := auth.ForContext(ctx)
	if !ok {
		return 0, domain.ErrForbidden
	}
	tid, err := parseIntID("id", obj.ID)
	if err != nil {
		return 0, err
	}
	seq, err := r.Messaging.MaxSeq(ctx, actor.ID, tid)
	if err != nil {
		return 0, err
	}
	return int(seq), nil
}

// MyLastReadSeq is the resolver for the myLastReadSeq field.
func (r *messageThreadResolver) MyLastReadSeq(ctx context.Context, obj *model.MessageThread) (int, error) {
	actor, ok := auth.ForContext(ctx)
	if !ok {
		return 0, domain.ErrForbidden
	}
	return int(lastReadSeqFor(obj.Src, actor.ID)), nil
}

// UnreadCount is the resolver for the unreadCount field.
func (r *messageThreadResolver) UnreadCount(ctx context.Context, obj *model.MessageThread) (int, error) {
	actor, ok := auth.ForContext(ctx)
	if !ok {
		return 0, domain.ErrForbidden
	}
	tid, err := parseIntID("id", obj.ID)
	if err != nil {
		return 0, err
	}
	latest, err := r.Messaging.MaxSeq(ctx, actor.ID, tid)
	if err != nil {
		return 0, err
	}
	unread := latest - lastReadSeqFor(obj.Src, actor.ID)
	if unread < 0 {
		unread = 0
	}
	return int(unread), nil
}

// CreateMessageThread is the resolver for the createMessageThread field.
func (r *mutationResolver) CreateMessageThread(ctx context.Context, input model.CreateMessageThreadInput) (*model.MessageThread, error) {
	actor, ok := auth.ForContext(ctx)
	if !ok {
		return nil, domain.ErrForbidden
	}
	ids := make([]int, 0, len(input.ParticipantUserIds))
	for _, raw := range input.ParticipantUserIds {
		id, err := parseIntID("participantUserIds", raw)
		if err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	thread, err := r.Messaging.CreateThread(ctx, actor.ID, ids, input.Title)
	if err != nil {
		return nil, err
	}
	return messageThreadToModel(thread), nil
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, input model.SendMessageInput) (*model.Message, error) {
	actor, ok := auth.ForContext(ctx)
	if !ok {
		return nil, domain.ErrForbidden
	}
	tid, err := parseIntID("threadId", input.ThreadID)
	if err != nil {
		return nil, err
	}
	msg, err := r.Messaging.SendMessage(ctx, actor.ID, portservices.SendMessageInput{
		ThreadID:    tid,
		Body:        input.Body,
		ClientNonce: input.ClientNonce,
	})
	if err != nil {
		return nil, err
	}
	return messageToModel(*msg), nil
}

// MarkThreadRead is the resolver for the markThreadRead field.
func (r *mutationResolver) MarkThreadRead(ctx context.Context, threadID string, seq int) (*model.MessageThread, error) {
	actor, ok := auth.ForContext(ctx)
	if !ok {
		return nil, domain.ErrForbidden
	}
	tid, err := parseIntID("threadId", threadID)
	if err != nil {
		return nil, err
	}
	thread, err := r.Messaging.MarkRead(ctx, actor.ID, tid, int64(seq))
	if err != nil {
		return nil, err
	}
	return messageThreadToModel(thread), nil
}

// SetTyping is the resolver for the setTyping field.
func (r *mutationResolver) SetTyping(ctx context.Context, threadID string, typing bool) (bool, error) {
	actor, ok := auth.ForContext(ctx)
	if !ok {
		return false, domain.ErrForbidden
	}
	tid, err := parseIntID("threadId", threadID)
	if err != nil {
		return false, err
	}
	if err := r.Messaging.SetTyping(ctx, actor.ID, tid, typing); err != nil {
		return false, err
	}
	return true, nil
}

// AddThreadParticipants is the resolver for the addThreadParticipants field.
func (r *mutationResolver) AddThreadParticipants(ctx context.Context, threadID string, userIds []string) (*model.MessageThread, error) {
	actor, ok := auth.ForContext(ctx)
	if !ok {
		return nil, domain.ErrForbidden
	}
	tid, err := parseIntID("threadId", threadID)
	if err != nil {
		return nil, err
	}
	ids := make([]int, 0, len(userIds))
	for _, raw := range userIds {
		id, err := parseIntID("userIds", raw)
		if err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	thread, err := r.Messaging.AddParticipants(ctx, actor.ID, tid, ids)
	if err != nil {
		return nil, err
	}
	return messageThreadToModel(thread), nil
}

// LeaveThread is the resolver for the leaveThread field.
func (r *mutationResolver) LeaveThread(ctx context.Context, threadID string) (bool, error) {
	actor, ok := auth.ForContext(ctx)
	if !ok {
		return false, domain.ErrForbidden
	}
	tid, err := parseIntID("threadId", threadID)
	if err != nil {
		return false, err
	}
	if err := r.Messaging.LeaveThread(ctx, actor.ID, tid); err != nil {
		return false, err
	}
	return true, nil
}

// MessageThreads is the resolver for the messageThreads field.
func (r *queryResolver) MessageThreads(ctx context.Context, first *int, before *string) ([]*model.MessageThread, error) {
	actor, ok := auth.ForContext(ctx)
	if !ok {
		return nil, domain.ErrForbidden
	}
	var beforeAt *time.Time
	if before != nil && *before != "" {
		t, err := time.Parse(time.RFC3339, *before)
		if err != nil {
			return nil, fmt.Errorf("%w: before must be an RFC3339 timestamp", domain.ErrInvalidInput)
		}
		beforeAt = &t
	}
	threads, err := r.Messaging.ListThreads(ctx, actor.ID, pageLimit(first), beforeAt)
	if err != nil {
		return nil, err
	}
	out := make([]*model.MessageThread, 0, len(threads))
	for i := range threads {
		out = append(out, messageThreadToModel(&threads[i]))
	}
	return out, nil
}

// MessageThread is the resolver for the messageThread field.
func (r *queryResolver) MessageThread(ctx context.Context, id string) (*model.MessageThread, error) {
	actor, ok := auth.ForContext(ctx)
	if !ok {
		return nil, domain.ErrForbidden
	}
	tid, err := parseIntID("id", id)
	if err != nil {
		return nil, err
	}
	thread, err := r.Messaging.GetThread(ctx, actor.ID, tid)
	if err != nil {
		return nil, err
	}
	return messageThreadToModel(thread), nil
}

// ThreadMessages is the resolver for the threadMessages field.
func (r *queryResolver) ThreadMessages(ctx context.Context, threadID string, first *int, before *int) (*model.MessageConnection, error) {
	actor, ok := auth.ForContext(ctx)
	if !ok {
		return nil, domain.ErrForbidden
	}
	tid, err := parseIntID("threadId", threadID)
	if err != nil {
		return nil, err
	}
	var beforeSeq *int64
	if before != nil {
		v := int64(*before)
		beforeSeq = &v
	}
	limit := pageLimit(first)
	msgs, err := r.Messaging.GetHistory(ctx, actor.ID, tid, limit, beforeSeq)
	if err != nil {
		return nil, err
	}

	items := make([]*model.Message, 0, len(msgs))
	for _, m := range msgs {
		items = append(items, messageToModel(m))
	}

	// History pages backwards from newest; a full page implies more to load.
	page := &model.PageInfo{
		HasNextPage:     false,
		HasPreviousPage: len(msgs) == limit,
	}
	if len(items) > 0 {
		start := items[0].ID
		end := items[len(items)-1].ID
		page.StartCursor = &start
		page.EndCursor = &end
	}
	return &model.MessageConnection{Items: items, PageInfo: page}, nil
}

// ThreadEvents is the resolver for the threadEvents field.
func (r *subscriptionResolver) ThreadEvents(ctx context.Context, threadID string, sinceSeq *int) (<-chan model.ThreadEvent, error) {
	actor, ok := auth.ForContext(ctx)
	if !ok {
		return nil, domain.ErrForbidden
	}
	tid, err := parseIntID("threadId", threadID)
	if err != nil {
		return nil, err
	}
	if err := r.Messaging.AssertParticipant(ctx, actor.ID, tid); err != nil {
		return nil, err
	}

	out := make(chan model.ThreadEvent, subscriptionBuffer)
	domainCh, unsub := r.Hub.Subscribe(tid)

	go func() {
		// out is written only by this goroutine and closed only here, so a send
		// on a closed channel is impossible. unsub drains us from the hub, so
		// the hub never blocks once we return.
		defer close(out)
		defer unsub()

		// Replay missed history first when the client supplies a cursor.
		if sinceSeq != nil {
			msgs, err := r.Messaging.ListSince(ctx, actor.ID, tid, int64(*sinceSeq))
			if err == nil {
				for _, m := range msgs {
					select {
					case out <- model.MessagePosted{Message: messageToModel(m)}:
					case <-ctx.Done():
						return
					}
				}
			}
		}

		for {
			select {
			case <-ctx.Done():
				return
			case evt, open := <-domainCh:
				if !open {
					// Hub dropped us (backpressure or listener reset) — tell the
					// client to re-sync, then end the stream.
					select {
					case out <- model.StreamReset{ThreadID: threadID}:
					case <-ctx.Done():
					}
					return
				}
				mapped := toModelThreadEvent(evt)
				if mapped == nil {
					continue
				}
				select {
				case out <- mapped:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// InboxEvents is the resolver for the inboxEvents field.
func (r *subscriptionResolver) InboxEvents(ctx context.Context) (<-chan *model.InboxEvent, error) {
	actor, ok := auth.ForContext(ctx)
	if !ok {
		return nil, domain.ErrForbidden
	}

	out := make(chan *model.InboxEvent, subscriptionBuffer)
	domainCh, unsub := r.Hub.SubscribeInbox(actor.ID)

	go func() {
		defer close(out)
		defer unsub()
		for {
			select {
			case <-ctx.Done():
				return
			case evt, open := <-domainCh:
				if !open {
					return
				}
				select {
				case out <- inboxEventToModel(evt):
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// User is the resolver for the user field.
func (r *threadParticipantResolver) User(ctx context.Context, obj *model.ThreadParticipant) (*model.User, error) {
	if _, ok := auth.ForContext(ctx); !ok {
		return nil, domain.ErrForbidden
	}
	u, err := r.UserService.GetByID(ctx, obj.SrcUserID)
	if err != nil {
		return nil, err
	}
	return userDomainToModel(u), nil
}

// Message returns generated.MessageResolver implementation.
func (r *Resolver) Message() generated.MessageResolver { return &messageResolver{r} }

// MessageThread returns generated.MessageThreadResolver implementation.
func (r *Resolver) MessageThread() generated.MessageThreadResolver { return &messageThreadResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

// ThreadParticipant returns generated.ThreadParticipantResolver implementation.
func (r *Resolver) ThreadParticipant() generated.ThreadParticipantResolver {
	return &threadParticipantResolver{r}
}

type messageResolver struct{ *Resolver }
type messageThreadResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type threadParticipantResolver struct{ *Resolver }
