package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"strconv"

	"github.com/CodeWarrior-debug/perspectize/backend/internal/adapters/auth"
	"github.com/CodeWarrior-debug/perspectize/backend/internal/adapters/graphql/generated"
	"github.com/CodeWarrior-debug/perspectize/backend/internal/adapters/graphql/model"
	"github.com/CodeWarrior-debug/perspectize/backend/internal/core/domain"
	portservices "github.com/CodeWarrior-debug/perspectize/backend/internal/core/ports/services"
)

// PrimaryCategory is the resolver for the primaryCategory field.
func (r *contentResolver) PrimaryCategory(ctx context.Context, obj *model.Content) (*model.Category, error) {
	// Parse content ID to look up PrimaryCategoryID from domain
	contentID, err := strconv.Atoi(obj.ID)
	if err != nil {
		return nil, nil
	}

	// Fetch the content to get PrimaryCategoryID
	content, err := r.ContentService.GetByID(ctx, contentID)
	if err != nil {
		return nil, nil
	}

	if content.PrimaryCategoryID == nil {
		return nil, nil
	}

	category, err := r.CategoryService.GetCategoryByID(ctx, *content.PrimaryCategoryID)
	if err != nil {
		slog.Error("resolving primary category failed", "contentID", contentID, "categoryID", *content.PrimaryCategoryID, "error", err)
		return nil, nil
	}

	return categoryDomainToModel(category), nil
}

// CreateContentFromYouTube is the resolver for the createContentFromYouTube field.
func (r *mutationResolver) CreateContentFromYouTube(ctx context.Context, input model.CreateContentFromYouTubeInput) (*model.CreateContentResult, error) {
	// Use authenticated user when userID is not provided or zero (mirrors CreatePerspective)
	userID := input.UserID
	if userID == 0 {
		authUser, err := auth.RequireAuth(ctx)
		if err != nil {
			return nil, fmt.Errorf("access denied: authentication required")
		}
		userID = authUser.ID
	}

	content, err := r.ContentService.CreateFromYouTube(ctx, input.URL, userID)

	// Handle idempotent duplicate: service returns (content, ErrAlreadyExists)
	if errors.Is(err, domain.ErrAlreadyExists) && content != nil {
		return &model.CreateContentResult{
			Content:        domainToModel(content),
			AlreadyExisted: true,
		}, nil
	}

	if err != nil {
		if errors.Is(err, domain.ErrInvalidURL) {
			return nil, fmt.Errorf("invalid YouTube URL")
		}

		// Generic error for any other failure (including YouTube API errors)
		// Details are already logged server-side by service layer
		return nil, fmt.Errorf("failed to create content from YouTube")
	}

	return &model.CreateContentResult{
		Content:        domainToModel(content),
		AlreadyExisted: false,
	}, nil
}

// UpdateContentSourceData is the resolver for the updateContentSourceData field.
func (r *mutationResolver) UpdateContentSourceData(ctx context.Context, contentID int) (*model.Content, error) {
	content, err := r.ContentService.UpdateSourceData(ctx, contentID)
	if err != nil {
		if errors.Is(err, domain.ErrNotFound) {
			return nil, fmt.Errorf("content not found")
		}
		if errors.Is(err, domain.ErrInvalidInput) || errors.Is(err, domain.ErrInvalidURL) {
			return nil, fmt.Errorf("invalid content: %w", err)
		}

		// Generic error for any other failure (including YouTube API errors)
		// Details are already logged server-side by service layer
		return nil, fmt.Errorf("failed to update content source data")
	}

	return domainToModel(content), nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	email := ""
	if input.Email != nil {
		email = *input.Email
	}
	user, err := r.UserService.Create(ctx, input.Username, email)
	if err != nil {
		if errors.Is(err, domain.ErrAlreadyExists) {
			return nil, fmt.Errorf("user already exists: %w", err)
		}
		if errors.Is(err, domain.ErrInvalidInput) {
			return nil, fmt.Errorf("invalid input: %w", err)
		}
		slog.Error("creating user failed", "error", err)
		return nil, fmt.Errorf("failed to create user: %v", err)
	}

	return userDomainToModel(user), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	serviceInput := portservices.UpdateUserInput{
		ID:       input.ID,
		Username: input.Username,
		Email:    input.Email,
	}

	user, err := r.UserService.Update(ctx, serviceInput)
	if err != nil {
		if errors.Is(err, domain.ErrNotFound) {
			return nil, fmt.Errorf("user not found")
		}
		if errors.Is(err, domain.ErrAlreadyExists) {
			return nil, fmt.Errorf("user already exists: %w", err)
		}
		if errors.Is(err, domain.ErrInvalidInput) {
			return nil, fmt.Errorf("invalid input: %w", err)
		}
		if errors.Is(err, domain.ErrSentinelUser) {
			return nil, fmt.Errorf("cannot modify system user")
		}
		slog.Error("updating user failed", "error", err)
		return nil, fmt.Errorf("failed to update user: %v", err)
	}

	return userDomainToModel(user), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	intID, err := strconv.Atoi(id)
	if err != nil {
		return false, fmt.Errorf("invalid user ID: %s", id)
	}

	err = r.UserService.Delete(ctx, intID)
	if err != nil {
		if errors.Is(err, domain.ErrNotFound) {
			return false, fmt.Errorf("user not found")
		}
		if errors.Is(err, domain.ErrInvalidInput) {
			return false, fmt.Errorf("invalid user ID")
		}
		if errors.Is(err, domain.ErrDeleteSentinel) {
			return false, fmt.Errorf("cannot delete system user")
		}
		slog.Error("deleting user failed", "error", err)
		return false, fmt.Errorf("failed to delete user")
	}

	return true, nil
}

// CreatePerspective is the resolver for the createPerspective field.
func (r *mutationResolver) CreatePerspective(ctx context.Context, input model.CreatePerspectiveInput) (*model.Perspective, error) {
	// Use authenticated user when userID is not provided or zero
	userID := input.UserID
	if userID == 0 {
		authUser, err := auth.RequireAuth(ctx)
		if err != nil {
			return nil, fmt.Errorf("access denied: authentication required")
		}
		userID = authUser.ID
	}

	serviceInput := portservices.CreatePerspectiveInput{
		UserID:                userID,
		Quality:               input.Quality,
		Agreement:             input.Agreement,
		Importance:            input.Importance,
		Confidence:            input.Confidence,
		Like:                  input.Like,
		Privacy:               input.Privacy,
		Description:           input.Description,
		Category:              input.Category,
		Parts:                 input.Parts,
		Labels:                input.Labels,
		PrimaryPerspectiveID:  input.PrimaryPerspectiveID,
		RelatedPerspectiveIDs: input.RelatedPerspectiveIDs,
		Review:                input.Review,
	}

	if input.ContentID != nil {
		serviceInput.ContentID = input.ContentID
	}

	// Convert customFields map to JSON
	if input.CustomFields != nil {
		data, err := json.Marshal(input.CustomFields)
		if err == nil {
			serviceInput.CustomFields = data
		}
	}

	// Convert categorized ratings
	if len(input.CategorizedRatings) > 0 {
		serviceInput.CategorizedRatings = make([]domain.CategorizedRating, len(input.CategorizedRatings))
		for i, cr := range input.CategorizedRatings {
			serviceInput.CategorizedRatings[i] = domain.CategorizedRating{
				Category: cr.Category,
				Rating:   cr.Rating,
			}
		}
	}

	perspective, err := r.PerspectiveService.Create(ctx, serviceInput)
	if err != nil {
		if errors.Is(err, domain.ErrInvalidRating) {
			return nil, fmt.Errorf("invalid rating: %w", err)
		}
		if errors.Is(err, domain.ErrInvalidInput) {
			return nil, fmt.Errorf("invalid input: %w", err)
		}
		if errors.Is(err, domain.ErrNotFound) {
			return nil, fmt.Errorf("user not found: %w", err)
		}
		slog.Error("creating perspective failed", "error", err)
		return nil, fmt.Errorf("failed to create perspective: %v", err)
	}

	return perspectiveDomainToModel(perspective), nil
}

// UpdatePerspective is the resolver for the updatePerspective field.
func (r *mutationResolver) UpdatePerspective(ctx context.Context, input model.UpdatePerspectiveInput) (*model.Perspective, error) {
	serviceInput := portservices.UpdatePerspectiveInput{
		ID:                    input.ID,
		Quality:               input.Quality,
		Agreement:             input.Agreement,
		Importance:            input.Importance,
		Confidence:            input.Confidence,
		Like:                  input.Like,
		Privacy:               input.Privacy,
		Description:           input.Description,
		Category:              input.Category,
		ReviewStatus:          input.ReviewStatus,
		Parts:                 input.Parts,
		Labels:                input.Labels,
		PrimaryPerspectiveID:  input.PrimaryPerspectiveID,
		RelatedPerspectiveIDs: input.RelatedPerspectiveIDs,
		Review:                input.Review,
	}

	if input.ContentID != nil {
		serviceInput.ContentID = input.ContentID
	}

	// Convert customFields map to JSON
	if input.CustomFields != nil {
		data, err := json.Marshal(input.CustomFields)
		if err == nil {
			serviceInput.CustomFields = data
		}
	}

	// Convert categorized ratings
	if len(input.CategorizedRatings) > 0 {
		serviceInput.CategorizedRatings = make([]domain.CategorizedRating, len(input.CategorizedRatings))
		for i, cr := range input.CategorizedRatings {
			serviceInput.CategorizedRatings[i] = domain.CategorizedRating{
				Category: cr.Category,
				Rating:   cr.Rating,
			}
		}
	}

	perspective, err := r.PerspectiveService.Update(ctx, serviceInput)
	if err != nil {
		if errors.Is(err, domain.ErrNotFound) {
			return nil, fmt.Errorf("perspective not found")
		}
		if errors.Is(err, domain.ErrInvalidRating) {
			return nil, fmt.Errorf("invalid rating: %w", err)
		}
		if errors.Is(err, domain.ErrInvalidInput) {
			return nil, fmt.Errorf("invalid input: %w", err)
		}
		slog.Error("updating perspective failed", "error", err)
		return nil, fmt.Errorf("failed to update perspective: %v", err)
	}

	return perspectiveDomainToModel(perspective), nil
}

// DeletePerspective is the resolver for the deletePerspective field.
func (r *mutationResolver) DeletePerspective(ctx context.Context, id string) (bool, error) {
	intID, err := strconv.Atoi(id)
	if err != nil {
		return false, fmt.Errorf("invalid perspective ID: %s", id)
	}

	err = r.PerspectiveService.Delete(ctx, intID)
	if err != nil {
		if errors.Is(err, domain.ErrNotFound) {
			return false, fmt.Errorf("perspective not found")
		}
		if errors.Is(err, domain.ErrInvalidInput) {
			return false, fmt.Errorf("invalid perspective ID")
		}
		slog.Error("deleting perspective failed", "error", err)
		return false, fmt.Errorf("failed to delete perspective")
	}

	return true, nil
}

// CreateClaim is the resolver for the createClaim field.
func (r *mutationResolver) CreateClaim(ctx context.Context, input model.CreateClaimInput) (*model.Content, error) {
	content, err := r.ContentService.CreateClaim(ctx, portservices.CreateClaimInput{
		Text:            input.Text,
		UserID:          input.UserID,
		ParentContentID: input.ParentContentID,
	})
	if err != nil {
		if errors.Is(err, domain.ErrInvalidInput) {
			return nil, fmt.Errorf("invalid input: %w", err)
		}
		if errors.Is(err, domain.ErrNotFound) {
			return nil, fmt.Errorf("parent content not found")
		}
		slog.Error("creating claim failed",
			"error", err,
			"userID", input.UserID,
			"parentContentID", input.ParentContentID,
		)
		return nil, fmt.Errorf("failed to create claim: %v", err)
	}

	return domainToModel(content), nil
}

// SetPrimaryCategory is the resolver for the setPrimaryCategory field.
func (r *mutationResolver) SetPrimaryCategory(ctx context.Context, input model.SetPrimaryCategoryInput) (*model.Content, error) {
	description := ""
	if input.Description != nil {
		description = *input.Description
	}
	entityType := ""
	if input.EntityType != nil {
		entityType = *input.EntityType
	}

	serviceInput := portservices.SetPrimaryCategoryInput{
		ContentID:   input.ContentID,
		QID:         input.Qid,
		Label:       input.Label,
		Description: description,
		EntityType:  entityType,
	}

	content, err := r.CategoryService.SetPrimaryCategory(ctx, serviceInput)
	if err != nil {
		if errors.Is(err, domain.ErrInvalidInput) {
			return nil, fmt.Errorf("invalid input: %w", err)
		}
		if errors.Is(err, domain.ErrNotFound) {
			return nil, fmt.Errorf("content not found")
		}
		slog.Error("setting primary category failed", "error", err, "contentID", input.ContentID)
		return nil, fmt.Errorf("failed to set primary category: %v", err)
	}

	return domainToModel(content), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	authUser, err := auth.RequireAuth(ctx)
	if err != nil {
		return nil, fmt.Errorf("access denied: authentication required")
	}

	user, err := r.UserService.GetByID(ctx, authUser.ID)
	if err != nil {
		if errors.Is(err, domain.ErrNotFound) {
			return nil, fmt.Errorf("user not found")
		}
		slog.Error("getting current user failed", "userID", authUser.ID, "error", err)
		return nil, fmt.Errorf("failed to get current user")
	}

	return userDomainToModel(user), nil
}

// ContentByID is the resolver for the contentByID field.
func (r *queryResolver) ContentByID(ctx context.Context, id string) (*model.Content, error) {
	intID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid content ID: %s", id)
	}

	content, err := r.ContentService.GetByID(ctx, intID)
	if err != nil {
		if errors.Is(err, domain.ErrNotFound) {
			return nil, fmt.Errorf("content not found with ID: %s", id)
		}
		if errors.Is(err, domain.ErrInvalidInput) {
			return nil, fmt.Errorf("invalid content ID: %s", id)
		}
		slog.Error("getting content failed", "id", id, "error", err)
		return nil, fmt.Errorf("failed to get content")
	}

	return domainToModel(content), nil
}

// Content is the resolver for the content field.
func (r *queryResolver) Content(ctx context.Context, first *int, after *string, last *int, before *string, sortBy *domain.ContentSortBy, sortOrder *domain.SortOrder, includeTotalCount *bool, filter *model.ContentFilter) (*model.PaginatedContent, error) {
	params := domain.ContentListParams{
		First:  first,
		After:  after,
		Last:   last,
		Before: before,
	}

	// Map GraphQL enums to domain enums
	if sortBy != nil {
		params.SortBy = *sortBy
	} else {
		params.SortBy = domain.ContentSortByCreatedAt
	}

	if sortOrder != nil {
		params.SortOrder = *sortOrder
	} else {
		params.SortOrder = domain.SortOrderDesc
	}

	if includeTotalCount != nil {
		params.IncludeTotalCount = *includeTotalCount
	}

	// Map filter
	if filter != nil {
		params.Filter = &domain.ContentFilter{}
		if filter.ContentType != nil {
			params.Filter.ContentType = filter.ContentType
		}
		params.Filter.MinLengthSeconds = filter.MinLengthSeconds
		params.Filter.MaxLengthSeconds = filter.MaxLengthSeconds
		params.Filter.Search = filter.Search
		params.Filter.MinViewCount = filter.MinViewCount
		params.Filter.MaxViewCount = filter.MaxViewCount
		params.Filter.MinLikeCount = filter.MinLikeCount
		params.Filter.MaxLikeCount = filter.MaxLikeCount
		params.Filter.PublishedAfter = filter.PublishedAfter
		params.Filter.PublishedBefore = filter.PublishedBefore
		params.Filter.ChannelTitle = filter.ChannelTitle
		params.Filter.TagContains = filter.TagContains
		params.Filter.DescriptionSearch = filter.DescriptionSearch
		params.Filter.CreatedAfter = filter.CreatedAfter
		params.Filter.CreatedBefore = filter.CreatedBefore
		params.Filter.UpdatedAfter = filter.UpdatedAfter
		params.Filter.UpdatedBefore = filter.UpdatedBefore
	}

	result, err := r.ContentService.ListContent(ctx, params)
	if err != nil {
		if errors.Is(err, domain.ErrInvalidInput) {
			return nil, fmt.Errorf("invalid pagination parameters: %w", err)
		}
		slog.Error("listing content failed", "error", err)
		return nil, fmt.Errorf("failed to list content")
	}

	// Map domain result to GraphQL model
	items := make([]*model.Content, len(result.Items))
	for i, item := range result.Items {
		items[i] = domainToModel(item)
	}

	conn := &model.PaginatedContent{
		Items: items,
		PageInfo: &model.PageInfo{
			HasNextPage:     result.HasNext,
			HasPreviousPage: result.HasPrev,
			StartCursor:     result.StartCursor,
			EndCursor:       result.EndCursor,
		},
		TotalCount: result.TotalCount,
	}

	return conn, nil
}

// UserByID is the resolver for the userByID field.
func (r *queryResolver) UserByID(ctx context.Context, id string) (*model.User, error) {
	intID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %s", id)
	}

	user, err := r.UserService.GetByID(ctx, intID)
	if err != nil {
		if errors.Is(err, domain.ErrNotFound) {
			return nil, nil // Return null for not found (GraphQL convention)
		}
		if errors.Is(err, domain.ErrInvalidInput) {
			return nil, fmt.Errorf("invalid user ID: %s", id)
		}
		slog.Error("getting user failed", "id", id, "error", err)
		return nil, fmt.Errorf("failed to get user")
	}

	return userDomainToModel(user), nil
}

// UserByUsername is the resolver for the userByUsername field.
func (r *queryResolver) UserByUsername(ctx context.Context, username string) (*model.User, error) {
	user, err := r.UserService.GetByUsername(ctx, username)
	if err != nil {
		if errors.Is(err, domain.ErrNotFound) {
			return nil, nil // Return null for not found (GraphQL convention)
		}
		if errors.Is(err, domain.ErrInvalidInput) {
			return nil, fmt.Errorf("invalid username")
		}
		slog.Error("getting user by username failed", "username", username, "error", err)
		return nil, fmt.Errorf("failed to get user")
	}

	return userDomainToModel(user), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserService.ListAll(ctx)
	if err != nil {
		slog.Error("listing users failed", "error", err)
		return nil, fmt.Errorf("failed to list users")
	}

	// Convert domain users to GraphQL model users
	modelUsers := make([]*model.User, len(users))
	for i, user := range users {
		modelUsers[i] = userDomainToModel(user)
	}

	return modelUsers, nil
}

// WikidataSearch is the resolver for the wikidataSearch field.
func (r *queryResolver) WikidataSearch(ctx context.Context, query string, language *string, limit *int) ([]*model.WikidataSearchResult, error) {
	lang := ""
	if language != nil {
		lang = *language
	}
	lim := 0
	if limit != nil {
		lim = *limit
	}

	results, err := r.CategoryService.SearchWikidata(ctx, query, lang, lim)
	if err != nil {
		slog.Error("wikidata search failed", "error", err, "query", query)
		return nil, fmt.Errorf("wikidata search failed: %v", err)
	}

	models := make([]*model.WikidataSearchResult, len(results))
	for i, r := range results {
		models[i] = &model.WikidataSearchResult{
			Qid:         r.QID,
			Label:       r.Label,
			Description: &r.Description,
			EntityType:  &r.EntityType,
		}
	}

	return models, nil
}

// PerspectiveByID is the resolver for the perspectiveByID field.
func (r *queryResolver) PerspectiveByID(ctx context.Context, id string) (*model.Perspective, error) {
	intID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid perspective ID: %s", id)
	}

	perspective, err := r.PerspectiveService.GetByID(ctx, intID)
	if err != nil {
		if errors.Is(err, domain.ErrNotFound) {
			return nil, nil // Return null for not found (GraphQL convention)
		}
		if errors.Is(err, domain.ErrInvalidInput) {
			return nil, fmt.Errorf("invalid perspective ID: %s", id)
		}
		slog.Error("getting perspective failed", "id", id, "error", err)
		return nil, fmt.Errorf("failed to get perspective")
	}

	return perspectiveDomainToModel(perspective), nil
}

// Perspectives is the resolver for the perspectives field.
func (r *queryResolver) Perspectives(ctx context.Context, first *int, after *string, last *int, before *string, sortBy *domain.PerspectiveSortBy, sortOrder *domain.SortOrder, includeTotalCount *bool, filter *model.PerspectiveFilter) (*model.PaginatedPerspectives, error) {
	params := domain.PerspectiveListParams{
		First:  first,
		After:  after,
		Last:   last,
		Before: before,
	}

	// Map GraphQL enums to domain enums
	if sortBy != nil {
		params.SortBy = *sortBy
	} else {
		params.SortBy = domain.PerspectiveSortByCreatedAt
	}

	if sortOrder != nil {
		params.SortOrder = *sortOrder
	} else {
		params.SortOrder = domain.SortOrderDesc
	}

	if includeTotalCount != nil {
		params.IncludeTotalCount = *includeTotalCount
	}

	// Map filter
	if filter != nil {
		params.Filter = &domain.PerspectiveFilter{}
		if filter.UserID != nil {
			params.Filter.UserID = filter.UserID
		}
		if filter.ContentID != nil {
			params.Filter.ContentID = filter.ContentID
		}
		if filter.Privacy != nil {
			params.Filter.Privacy = filter.Privacy
		}
	}

	result, err := r.PerspectiveService.ListPerspectives(ctx, params)
	if err != nil {
		if errors.Is(err, domain.ErrInvalidInput) {
			return nil, fmt.Errorf("invalid pagination parameters: %w", err)
		}
		slog.Error("listing perspectives failed", "error", err)
		return nil, fmt.Errorf("failed to list perspectives")
	}

	// Map domain result to GraphQL model
	items := make([]*model.Perspective, len(result.Items))
	for i, item := range result.Items {
		items[i] = perspectiveDomainToModel(item)
	}

	conn := &model.PaginatedPerspectives{
		Items: items,
		PageInfo: &model.PageInfo{
			HasNextPage:     result.HasNext,
			HasPreviousPage: result.HasPrev,
			StartCursor:     result.StartCursor,
			EndCursor:       result.EndCursor,
		},
		TotalCount: result.TotalCount,
	}

	return conn, nil
}

// Email is the resolver for the email field.
// Returns email only when the authenticated user is requesting their own account (H-10).
func (r *userResolver) Email(ctx context.Context, obj *model.User) (*string, error) {
	authenticatedUser, authenticated := auth.ForContext(ctx)
	if !authenticated {
		return nil, nil
	}

	// Compare authenticated user ID with the requested user's ID
	requestedUserID, err := strconv.Atoi(obj.ID)
	if err != nil {
		return nil, nil
	}

	if authenticatedUser.ID != requestedUserID {
		return nil, nil // Not own account — hide email
	}

	return obj.Email, nil
}

// Content returns generated.ContentResolver implementation.
func (r *Resolver) Content() generated.ContentResolver { return &contentResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type contentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
