onlyBuiltDependencies:
  - '@clerk/shared'
  - esbuild

overrides:
  rollup: ^4.59.0
  minimatch: ^10.2.3
  serialize-javascript: ^7.0.3
  tar: ^7.5.11
  undici: ^7.24.0
  devalue: ^5.8.1
  'tinyglobby>picomatch': ^4.0.4
  js-cookie: ^3.0.7
  postcss: ^8.5.10
  cookie: ^0.7.0
