package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/yourorg/perspectize-go/internal/adapters/graphql/generated"
	"github.com/yourorg/perspectize-go/internal/adapters/graphql/model"
	"github.com/yourorg/perspectize-go/internal/adapters/youtube"
	"github.com/yourorg/perspectize-go/internal/core/domain"
)

// CreateContentFromYouTube is the resolver for the createContentFromYouTube field.
func (r *mutationResolver) CreateContentFromYouTube(ctx context.Context, input model.CreateContentFromYouTubeInput) (*model.Content, error) {
	content, err := r.ContentService.CreateFromYouTube(ctx, input.URL, youtube.ExtractVideoID)
	if err != nil {
		if errors.Is(err, domain.ErrAlreadyExists) {
			return nil, fmt.Errorf("content already exists for this URL")
		}
		if errors.Is(err, domain.ErrInvalidURL) {
			return nil, fmt.Errorf("invalid YouTube URL")
		}
		return nil, fmt.Errorf("failed to create content: %w", err)
	}

	return domainToModel(content), nil
}

// Content is the resolver for the content field.
func (r *queryResolver) Content(ctx context.Context, id string) (*model.Content, error) {
	intID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid content ID: %s", id)
	}

	content, err := r.ContentService.GetByID(ctx, intID)
	if err != nil {
		if errors.Is(err, domain.ErrNotFound) {
			return nil, fmt.Errorf("content not found with ID: %s", id)
		}
		if errors.Is(err, domain.ErrInvalidInput) {
			return nil, fmt.Errorf("invalid content ID: %s", id)
		}
		return nil, fmt.Errorf("failed to get content: %w", err)
	}

	return domainToModel(content), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
