// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/CodeWarrior-debug/perspectize/backend/internal/core/domain"
)

type ThreadEvent interface {
	IsThreadEvent()
}

type CategorizedRating struct {
	Category string `json:"category"`
	Rating   int    `json:"rating"`
}

type CategorizedRatingInput struct {
	Category string `json:"category"`
	Rating   int    `json:"rating"`
}

type Category struct {
	ID          string  `json:"id"`
	WikidataQid string  `json:"wikidataQid"`
	Label       string  `json:"label"`
	Description *string `json:"description,omitempty"`
	EntityType  *string `json:"entityType,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type Content struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	URL             *string        `json:"url,omitempty"`
	ContentType     string         `json:"contentType"`
	AddedByUserID   string         `json:"addedByUserID"`
	AddedBy         *User          `json:"addedBy,omitempty"`
	Length          *int           `json:"length,omitempty"`
	LengthUnits     *string        `json:"lengthUnits,omitempty"`
	ViewCount       *int           `json:"viewCount,omitempty"`
	LikeCount       *int           `json:"likeCount,omitempty"`
	CommentCount    *int           `json:"commentCount,omitempty"`
	ChannelTitle    *string        `json:"channelTitle,omitempty"`
	PublishedAt     *string        `json:"publishedAt,omitempty"`
	Tags            []string       `json:"tags,omitempty"`
	Description     *string        `json:"description,omitempty"`
	Response        map[string]any `json:"response,omitempty"`
	PrimaryCategory *Category      `json:"primaryCategory,omitempty"`
	CreatedAt       string         `json:"createdAt"`
	UpdatedAt       string         `json:"updatedAt"`
}

type ContentFilter struct {
	ContentType       *domain.ContentType `json:"contentType,omitempty"`
	MinLengthSeconds  *int                `json:"minLengthSeconds,omitempty"`
	MaxLengthSeconds  *int                `json:"maxLengthSeconds,omitempty"`
	Search            *string             `json:"search,omitempty"`
	MinViewCount      *int                `json:"minViewCount,omitempty"`
	MaxViewCount      *int                `json:"maxViewCount,omitempty"`
	MinLikeCount      *int                `json:"minLikeCount,omitempty"`
	MaxLikeCount      *int                `json:"maxLikeCount,omitempty"`
	PublishedAfter    *string             `json:"publishedAfter,omitempty"`
	PublishedBefore   *string             `json:"publishedBefore,omitempty"`
	ChannelTitle      *string             `json:"channelTitle,omitempty"`
	TagContains       *string             `json:"tagContains,omitempty"`
	DescriptionSearch *string             `json:"descriptionSearch,omitempty"`
	CreatedAfter      *string             `json:"createdAfter,omitempty"`
	CreatedBefore     *string             `json:"createdBefore,omitempty"`
	UpdatedAfter      *string             `json:"updatedAfter,omitempty"`
	UpdatedBefore     *string             `json:"updatedBefore,omitempty"`
}

type CreateClaimInput struct {
	Text            string `json:"text"`
	UserID          int    `json:"userID"`
	ParentContentID int    `json:"parentContentID"`
}

type CreateContentFromYouTubeInput struct {
	URL    string `json:"url"`
	UserID int    `json:"userId"`
}

type CreateContentResult struct {
	Content        *Content `json:"content"`
	AlreadyExisted bool     `json:"alreadyExisted"`
}

type CreateMessageThreadInput struct {
	ParticipantUserIds []string `json:"participantUserIds"`
	Title              *string  `json:"title,omitempty"`
}

type CreatePerspectiveInput struct {
	UserID                int                       `json:"userID"`
	ContentID             *int                      `json:"contentID,omitempty"`
	Quality               *int                      `json:"quality,omitempty"`
	Agreement             *int                      `json:"agreement,omitempty"`
	Importance            *int                      `json:"importance,omitempty"`
	Confidence            *int                      `json:"confidence,omitempty"`
	Like                  *string                   `json:"like,omitempty"`
	Privacy               *domain.Privacy           `json:"privacy,omitempty"`
	Description           *string                   `json:"description,omitempty"`
	Category              *string                   `json:"category,omitempty"`
	Parts                 []int                     `json:"parts,omitempty"`
	Labels                []string                  `json:"labels,omitempty"`
	CategorizedRatings    []*CategorizedRatingInput `json:"categorizedRatings,omitempty"`
	PrimaryPerspectiveID  *int                      `json:"primaryPerspectiveID,omitempty"`
	RelatedPerspectiveIDs []int                     `json:"relatedPerspectiveIDs,omitempty"`
	CustomFields          map[string]any            `json:"customFields,omitempty"`
	Review                *string                   `json:"review,omitempty"`
}

type CreateUserInput struct {
	Username string  `json:"username"`
	Email    *string `json:"email,omitempty"`
}

type InboxEvent struct {
	ThreadID      string `json:"threadId"`
	LastMessageAt string `json:"lastMessageAt"`
	LatestSeq     int    `json:"latestSeq"`
	UnreadCount   int    `json:"unreadCount"`
}

type MessageConnection struct {
	Items    []*Message `json:"items"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type MessagePosted struct {
	Message *Message `json:"message"`
}

func (MessagePosted) IsThreadEvent() {}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type PaginatedContent struct {
	Items      []*Content `json:"items"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount *int       `json:"totalCount,omitempty"`
}

type PaginatedPerspectives struct {
	Items      []*Perspective `json:"items"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount *int           `json:"totalCount,omitempty"`
}

type ParticipantChanged struct {
	ThreadID string                `json:"threadId"`
	UserID   string                `json:"userId"`
	Change   ParticipantChangeKind `json:"change"`
}

func (ParticipantChanged) IsThreadEvent() {}

type Perspective struct {
	ID                    string               `json:"id"`
	UserID                string               `json:"userID"`
	User                  *User                `json:"user,omitempty"`
	ContentID             *string              `json:"contentID,omitempty"`
	Content               *Content             `json:"content,omitempty"`
	Quality               *int                 `json:"quality,omitempty"`
	Agreement             *int                 `json:"agreement,omitempty"`
	Importance            *int                 `json:"importance,omitempty"`
	Confidence            *int                 `json:"confidence,omitempty"`
	Like                  *string              `json:"like,omitempty"`
	Privacy               domain.Privacy       `json:"privacy"`
	Description           *string              `json:"description,omitempty"`
	Category              *string              `json:"category,omitempty"`
	ReviewStatus          *domain.ReviewStatus `json:"reviewStatus,omitempty"`
	Parts                 []int                `json:"parts,omitempty"`
	Labels                []string             `json:"labels,omitempty"`
	CategorizedRatings    []*CategorizedRating `json:"categorizedRatings,omitempty"`
	PrimaryPerspectiveID  *string              `json:"primaryPerspectiveID,omitempty"`
	RelatedPerspectiveIDs []int                `json:"relatedPerspectiveIDs,omitempty"`
	CustomFields          map[string]any       `json:"customFields,omitempty"`
	Review                *string              `json:"review,omitempty"`
	CreatedAt             string               `json:"createdAt"`
	UpdatedAt             string               `json:"updatedAt"`
}

type PerspectiveFilter struct {
	UserID    *int            `json:"userID,omitempty"`
	ContentID *int            `json:"contentID,omitempty"`
	Privacy   *domain.Privacy `json:"privacy,omitempty"`
}

type PresenceChanged struct {
	ThreadID string               `json:"threadId"`
	UserID   string               `json:"userId"`
	State    domain.PresenceState `json:"state"`
}

func (PresenceChanged) IsThreadEvent() {}

type Query struct {
}

type ReadReceiptChanged struct {
	ThreadID    string `json:"threadId"`
	UserID      string `json:"userId"`
	LastReadSeq int    `json:"lastReadSeq"`
}

func (ReadReceiptChanged) IsThreadEvent() {}

type SendMessageInput struct {
	ThreadID    string `json:"threadId"`
	Body        string `json:"body"`
	ClientNonce string `json:"clientNonce"`
}

type SetPrimaryCategoryInput struct {
	ContentID   int     `json:"contentId"`
	Qid         string  `json:"qid"`
	Label       string  `json:"label"`
	Description *string `json:"description,omitempty"`
	EntityType  *string `json:"entityType,omitempty"`
}

type StreamReset struct {
	ThreadID string `json:"threadId"`
}

func (StreamReset) IsThreadEvent() {}

type Subscription struct {
}

type TypingChanged struct {
	ThreadID string `json:"threadId"`
	UserID   string `json:"userId"`
	Typing   bool   `json:"typing"`
}

func (TypingChanged) IsThreadEvent() {}

type UpdatePerspectiveInput struct {
	ID                    int                       `json:"id"`
	ContentID             *int                      `json:"contentID,omitempty"`
	Quality               *int                      `json:"quality,omitempty"`
	Agreement             *int                      `json:"agreement,omitempty"`
	Importance            *int                      `json:"importance,omitempty"`
	Confidence            *int                      `json:"confidence,omitempty"`
	Like                  *string                   `json:"like,omitempty"`
	Privacy               *domain.Privacy           `json:"privacy,omitempty"`
	Description           *string                   `json:"description,omitempty"`
	Category              *string                   `json:"category,omitempty"`
	ReviewStatus          *domain.ReviewStatus      `json:"reviewStatus,omitempty"`
	Parts                 []int                     `json:"parts,omitempty"`
	Labels                []string                  `json:"labels,omitempty"`
	CategorizedRatings    []*CategorizedRatingInput `json:"categorizedRatings,omitempty"`
	PrimaryPerspectiveID  *int                      `json:"primaryPerspectiveID,omitempty"`
	RelatedPerspectiveIDs []int                     `json:"relatedPerspectiveIDs,omitempty"`
	CustomFields          map[string]any            `json:"customFields,omitempty"`
	Review                *string                   `json:"review,omitempty"`
}

type UpdateUserInput struct {
	ID       int     `json:"id"`
	Username *string `json:"username,omitempty"`
	Email    *string `json:"email,omitempty"`
}

type User struct {
	ID         string          `json:"id"`
	Username   string          `json:"username"`
	Email      *string         `json:"email,omitempty"`
	Active     bool            `json:"active"`
	Role       domain.UserRole `json:"role"`
	Onboarding *UserOnboarding `json:"onboarding"`
	CreatedAt  string          `json:"createdAt"`
	UpdatedAt  string          `json:"updatedAt"`
}

type UserOnboarding struct {
	Version            int     `json:"version"`
	DisplayNextSession bool    `json:"displayNextSession"`
	CompletedAt        *string `json:"completedAt,omitempty"`
}

type WikidataSearchResult struct {
	Qid         string  `json:"qid"`
	Label       string  `json:"label"`
	Description *string `json:"description,omitempty"`
	EntityType  *string `json:"entityType,omitempty"`
}

type ParticipantChangeKind string

const (
	ParticipantChangeKindAdded   ParticipantChangeKind = "ADDED"
	ParticipantChangeKindRemoved ParticipantChangeKind = "REMOVED"
)

var AllParticipantChangeKind = []ParticipantChangeKind{
	ParticipantChangeKindAdded,
	ParticipantChangeKindRemoved,
}

func (e ParticipantChangeKind) IsValid() bool {
	switch e {
	case ParticipantChangeKindAdded, ParticipantChangeKindRemoved:
		return true
	}
	return false
}

func (e ParticipantChangeKind) String() string {
	return string(e)
}

func (e *ParticipantChangeKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ParticipantChangeKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ParticipantChangeKind", str)
	}
	return nil
}

func (e ParticipantChangeKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ParticipantChangeKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ParticipantChangeKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
