services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - perspectize_data:/var/lib/postgresql/perspectize/data
volumes:
  perspectize_data: