import { COLUMNS, GROUP_LABELS, TYPES, type ColumnDef } from './catalog.js';
import { bindingFor, resolveGrid, typeLabel, type DraftState } from './model.js';

const YES = 'yes';
const NO = 'no';

function esc(v: string): string {
  return v.replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim();
}

function table(headers: string[], rows: string[][]): string {
  if (rows.length === 0) return '_none_\n';
  const head = `| ${headers.join(' | ')} |`;
  const sep = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.map((r) => `| ${r.map(esc).join(' | ')} |`).join('\n');
  return [head, sep, body].join('\n') + '\n';
}

function storageNote(col: ColumnDef): string {
  switch (col.storage) {
    case 'universal-column':
      return 'existing column on `content` — no migration';
    case 'jsonb':
      return '`response` JSONB — no migration';
    case 'promoted-column':
      return 'promote to a dedicated column — migration required';
    case 'derived':
      return 'computed at read time — not stored';
  }
}

export function buildSpec(state: DraftState): string {
  const d = state.draft;
  const grid = resolveGrid(state);
  const chosen = COLUMNS.filter((c) => state.decisions[c.id]);
  const rejected = COLUMNS.filter((c) => !state.decisions[c.id] && !c.pinned);
  const out: string[] = [];

  out.push(`# Content type spec: ${d.label || '(unnamed)'}`);
  out.push('');
  out.push(`Generated by \`tools/content-type-designer\`. Every line below is a decision that was made in the form — nothing here was inferred by a model.`);
  out.push('');

  out.push('## 1. Identity');
  out.push('');
  out.push(
    table(
      ['Decision', 'Value'],
      [
        ['Label', d.label],
        ['Plural', d.plural],
        ['GraphQL / domain enum', `\`${d.enumValue}\``],
        ['DB value (lowercased by the mapper)', `\`${d.enumValue.toLowerCase()}\``],
        ['What one row is', d.gist],
        ['Type icon', d.icon],
        ['Accent colour', d.accent]
      ]
    )
  );

  out.push('## 2. Ingestion & enrichment');
  out.push('');
  out.push(
    table(
      ['Decision', 'Value'],
      [
        ['Ingestion method', d.ingestion],
        ['Enrichment source', d.enrichment],
        ['URL required', d.urlRequired ? YES : NO],
        ['Accepted URL shapes', d.urlPattern],
        ['Natural identity / dedup key', d.identity],
        [
          'Cross-type URL uniqueness',
          d.sharesUrlSpace
            ? 'MUST relax the global `UNIQUE(url)` constraint — this type can share a URL with another type. Migration required: replace with `UNIQUE(url, content_type)` or a partial index.'
            : 'Keep the existing global `UNIQUE(url)` constraint.'
        ],
        ['Thumbnail strategy', d.thumbnail]
      ]
    )
  );
  if (d.ingestion === 'api' || d.ingestion === 'scrape') {
    out.push(
      `Adapter to build: \`backend/internal/adapters/${d.id}/\` (\`client.go\`, \`parser.go\`) behind a port interface in \`backend/internal/core/ports/services/\`, wired in \`cmd/server/main.go\`.`
    );
  } else if (d.ingestion === 'manual' || d.ingestion === 'url-only') {
    out.push('No external adapter. All fields come from the create form, so form validation is the only guard on data quality.');
  } else {
    out.push('No external adapter. The service resolves an existing `content` row (and a person record) instead of fetching.');
  }
  out.push('');

  out.push('## 3. Fields for this type');
  out.push('');
  out.push(
    table(
      ['Column', 'Label for this type', 'Applicability', 'Source', 'Value path', 'Unit', 'Storage', 'Sortable', 'Default on'],
      chosen.map((col) => {
        const b = state.decisions[col.id]!;
        return [
          col.id,
          b.label || col.generic,
          b.applicability,
          b.source,
          b.path,
          b.unit ?? '—',
          storageNote(col),
          col.sortable ? YES : NO,
          b.defaultVisible ? YES : NO
        ];
      })
    )
  );

  const migrations = chosen.filter((c) => c.storage === 'promoted-column');
  out.push(
    migrations.length > 0
      ? `**Migration needed** for: ${migrations.map((c) => `\`${c.id}\``).join(', ')} — these are shared with other types and queried, so they earn a dedicated column rather than a JSONB path.`
      : '**No migration needed** — every field lands in an existing column or in `response` JSONB.'
  );
  out.push('');
  const sortables = chosen.filter((c) => c.sortable && c.storage === 'jsonb');
  if (sortables.length > 0) {
    out.push('Sortable JSONB fields need a SQL extraction rule in `backend/internal/adapters/repositories/postgres/helpers.go` and a virtual GORM field in `gorm_models.go`:');
    out.push('');
    out.push(
      table(
        ['Sort enum', 'SQLRepr'],
        sortables.map((c) => {
          const b = state.decisions[c.id]!;
          return [`ContentSortBy${c.id[0].toUpperCase()}${c.id.slice(1)}`, `\`${b.path}\``];
        })
      )
    );
  }

  out.push('## 4. Fields deliberately not carried');
  out.push('');
  out.push(
    table(
      ['Column', 'Meaning elsewhere', 'Why not here'],
      rejected.map((col) => [
        col.generic || col.id,
        Object.entries(col.bindings)
          .slice(0, 3)
          .map(([t, b]) => `${typeLabel(t, d)}: ${b!.label}`)
          .join('; ') || '—',
        `n/a for ${d.label} — cells render "${col.gapFallback}" when this type appears alongside types that do bind it.`
      ])
    )
  );

  out.push('## 5. Default grid for the current selection');
  out.push('');
  out.push(`Selection: ${state.selected.map((t) => typeLabel(t, d)).join(', ') || '(none)'}`);
  out.push('');
  out.push(`Visibility rule: **${state.rule}** — a column is on by default when ${
    state.rule === 'any'
      ? 'any selected type defaults it on'
      : state.rule === 'all'
        ? 'every selected type defaults it on'
        : 'a majority of selected types default it on'
  }.`);
  out.push('');
  out.push(
    table(
      ['Header shown', 'Column id', 'Group', 'Populated for', 'Blank for', 'Gap render', 'Tooltip'],
      grid.visible.map((rc) => [
        rc.header || '(icon)',
        rc.col.id,
        GROUP_LABELS[rc.col.group],
        rc.bound.map((t) => typeLabel(t, d)).join(', '),
        rc.unbound.map((t) => typeLabel(t, d)).join(', ') || '—',
        rc.unbound.length ? rc.col.gapFallback : '—',
        rc.tooltip
      ])
    )
  );

  const multi = state.selected.length > 1;
  if (multi) {
    const aliased = grid.visible.filter((rc) => new Set(rc.aliases.map((a) => a.label)).size > 1);
    if (aliased.length) {
      out.push('### Per-type header aliases');
      out.push('');
      out.push('When exactly one type is filtered in, swap the generic header for the type-specific one:');
      out.push('');
      // Column-by-column alias rows, keyed off the full selection so every row
      // has the same arity even where a type has no binding.
      out.push(
        table(
          ['Column', 'Generic header', ...state.selected.map((t) => typeLabel(t, d))],
          aliased.map((rc) => [
            rc.col.id,
            rc.col.generic,
            ...state.selected.map((t) => {
              const a = rc.aliases.find((x) => x.typeId === t);
              if (!a) return '—';
              return a.unit ? `${a.label} (${a.unit})` : a.label;
            })
          ])
        )
      );
    }
  }

  out.push('## 6. Consistency review');
  out.push('');
  if (grid.warnings.length === 0) {
    out.push('No gaps flagged for this selection.');
  } else {
    for (const w of grid.warnings) {
      const tag = w.severity === 'error' ? 'MUST FIX' : w.severity === 'warn' ? 'GAP' : 'NOTE';
      out.push(`- **${tag}**${w.columnId ? ` (\`${w.columnId}\`)` : ''}: ${w.message}`);
    }
  }
  out.push('');

  out.push('## 7. Hidden-by-default columns (column picker)');
  out.push('');
  out.push(
    table(
      ['Column', 'Why it is off by default'],
      grid.columns.filter((rc) => !rc.visible && rc.bound.length > 0).map((rc) => [rc.col.generic || rc.col.id, rc.reason])
    )
  );

  out.push('## 8. Testing approach');
  out.push('');
  out.push(state.testingNotes.trim() || 'Follow the codebase instructions, then existing patterns, then judgment; stop and ask if genuinely unsure.');
  out.push('');
  if (state.deviations.trim()) {
    out.push('## 9. Conventions to ignore for this work only');
    out.push('');
    out.push(state.deviations.trim());
    out.push('');
  }

  out.push('## Implementation checklist');
  out.push('');
  const steps = [
    `Domain: add \`ContentType${d.label.replace(/[^A-Za-z0-9]/g, '')} ContentType = "${d.enumValue}"\` in \`backend/internal/core/domain/content.go\`.`,
    sortables.length
      ? `Domain: add sort enums in \`domain/pagination.go\` for ${sortables.map((c) => c.id).join(', ')}.`
      : 'Domain: no new sort enums.',
    d.ingestion === 'api' || d.ingestion === 'scrape'
      ? `Adapter: \`backend/internal/adapters/${d.id}/\` against ${d.enrichment}.`
      : 'Adapter: none.',
    `Schema: add \`${d.enumValue}\` to the ContentType enum and a \`createContentFrom${d.label.replace(/[^A-Za-z0-9]/g, '')}\` mutation + input in \`backend/schema.graphql\`, then \`make graphql-gen\`.`,
    `Service: \`CreateFrom${d.label.replace(/[^A-Za-z0-9]/g, '')}\` in \`content_service.go\` — dedupe on ${d.identity}, validate, enrich, persist.`,
    migrations.length
      ? `Migration: promote ${migrations.map((c) => c.id).join(', ')} to columns (check \`ls backend/migrations/ | tail -5\` for the next number).`
      : 'Migration: none.',
    d.sharesUrlSpace ? 'Migration: relax `UNIQUE(url)` to be type-scoped.' : 'Constraint: `UNIQUE(url)` unchanged.',
    'Repository: sort rules in `helpers.go`, virtual fields in `gorm_models.go`.',
    'Resolver: mutation handler in `schema.resolvers.go`.',
    'Frontend: types + queries in `src/lib/queries/content.ts`; mutation hook alongside `useAddVideo.ts`.',
    d.urlRequired ? `Frontend: URL validation for ${d.urlPattern} in \`src/lib/utils/\`.` : 'Frontend: form validation for the manual fields (no URL rule).',
    `Frontend: \`typeCellRenderer\` icon (${d.icon}) and \`itemCellRenderer\` tile (${d.thumbnail}) in \`src/lib/utils/formatting.ts\`.`,
    `Frontend: column defs + tooltips in \`ActivityTable.svelte\` per section 5, with the alias swap from the per-type header table.`,
    'Tests: domain enum, service create paths, resolver mutation + filter-by-type, formatting renderers, query definitions.',
    'Verify: `go build ./...`, `go test ./...`, `pnpm run test:run`.'
  ];
  for (const s of steps) out.push(`- [ ] ${s}`);
  out.push('');

  return out.join('\n');
}

/** Compact matrix of every seeded type against every column — the cross-type sanity check. */
export function buildMatrix(state: DraftState): string {
  const ids = [state.draft.id, ...TYPES.map((t) => t.id)];
  const rows = COLUMNS.map((col) => [
    col.generic || col.id,
    ...ids.map((id) => {
      const b = bindingFor(col, id, state);
      if (!b) return '—';
      return `${b.label || '·'}${b.defaultVisible ? ' ●' : ' ○'}`;
    })
  ]);
  return [
    '# Column × content type matrix',
    '',
    '● default-visible for that type, ○ available but off by default, — not applicable.',
    '',
    table(['Column', ...ids.map((id) => typeLabel(id, state.draft))], rows)
  ].join('\n');
}
